### ISSUE TITLE
GKE. Stackdriver Kubernetes Beta. Regional or Multizone Cluster do not show pods metrics.

### ISSUE THREAD

**Issue by vladimirkoval** [GoogleCloudPlatform/k8s-stackdriver#170]
Hi

I've to try to use new Stackdriver Kubernetes Beta monitoring for GKE cluster (region: us-east4) in the zonal cluster everything works great. All resources (pods, nodes, namespaces, services, deployments etc.) shows in  Stackdriver -> Resources -> Kubernets Beta. But if I try to use GKE in the regional cluster or multi-zone there is only aggregated metrics for namespaces and nothing about pods or nodes metrics.

I didn't find any cases or bug reports about this that's why I've opened the issue here. If this case should be redirected to GCP Support Team please let me know.

Thank you.

**Comment by kawych** [comment]
This is a known issue with a fix PR in flight: https://github.com/kubernetes/kubernetes/pull/65176. Once it's in, I'm going to cherry-pick it to 1.10 and 1.11.

The bug is related to Heapster configuration, so it's not related to this repository. I'm closing this issue, if you want to track this issue feel free to open a bug under k8s.io/heapster and assign it to me.
